servers:
  web:
    hosts:
      - 3.239.214.202

env:
  clear:
    NODE_ENV: production
    SOLANA_CLUSTER: devnet
    API_URL: https://api-main-devnet.dreader.io
    D_READER_URL: https://main-devnet.dreader.app
    D_PUBLISHER_URL: https://main-devnet.dpublisher.app
    WORKER_URL: workers.dreader.io
    CDN_URL: 