servers:
  web:
    hosts:
      - 52.90.126.198

env:
  clear:
    NODE_ENV: production
    SOLANA_CLUSTER: devnet
    API_URL: https://api-dev-devnet.dreader.io
    D_READER_URL: https://dev-devnet.dreader.app
    D_PUBLISHER_URL: https://dev-devnet.dpublisher.app
    WORKER_URL: dev.workers.dreader.io
    CDN_URL: 